### ISSUE TITLE
Working with Spotify 1.0.1.1060

### ISSUE THREAD

**Issue by Linell** [Linell/mjolnir.lb.spotify#2]
I updated this morning and none of the bindings work. I assume they've changed the way that Spotify interacts with AppleScript.

**Comment by elft3r** [comment]
Hey,
I stumbled over the same thing today. But after some investigation I found the [following link](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/Apple-scripting-broken-in-1-0-1-988-g8f17a348/td-p/1029434) which explains how to fix Spotify so that it works again.

**Comment by Linell** [comment]
Thanks @elft3r that worked for me!

For posterity, to resolve I modified line 51 of `~/../../Applications/Spotify.app/Contents/Info.plist` from `<string>Spotify.sdef</string>` to `<string>applescript/Spotify.sdef</string>` and it's working after restarting Spotify. Some of the comments in the link suggested that this may not work after restarting, though.
